const ActionType = {
    LOGIN_USER:"LOGIN_USER",
    REGISTER_USER:"REGISTER_USER",
    FORGOT_PASSWORD:"FORGOT_PASSWORD",
    CONTACTS:"CONTACTS",
    CONVERSATIONSTART:"CONVERSATION_START",
    GET_MESSAGE:"GET_MESSAGE",
    SEND_MESSAGE:"SEND_MESSAGE",
    DELETE_MESSAGE:"DELETE_MESSAGE",
    EDIT_MESSAGE:"EDIT_MESSAGE",
    USER_PROFILE:"USER_PROFILE"
}

export default ActionType